name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"

jobs:
  test:
    name: integration test ${{ matrix.python-version }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Switch to Current Branch
        run: git checkout ${{ env.BRANCH }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get install darcs git
          python -m pip install --upgrade pip
          python -m pip install --upgrade poetry
          poetry install
          darcs --version
      - name: Run integration test
        run: |
          rm -rf _darcs
          poetry run git-darcs update -nw -v 2>&1
          darcs show tags | grep -q git-checkpoint
          darcs show tags
          rm -rf _darcs
          poetry run git-darcs update -nw -v -ns 2>&1
          darcs show tags | grep -q git-checkpoint
          darcs show tags
          poetry run git-darcs clone . git-darcs-clone -v
          rm -rf git-darcs-clone
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          export gpath="$(pwd)"
          echo poetry run sh -c "cd ..; mkdir test; cd test; darcs init; git init; git-darcs pull -a -nw -v $gpath"
          poetry run sh -c "cd ..; mkdir test; cd test; darcs init; git init; git-darcs pull -a -nw -v $gpath"
          cd ..
          rm -rf test
      - name: Run black
        run: poetry run black --check .
      - name: Run flake8
        run: poetry run flake8 --exclude .venv
